### ISSUE TITLE
Cannot install driftpy with pip install

### ISSUE THREAD

**Issue by albertwong08** [drift-labs/driftpy#137]
When I try to install driftpy using pip install, I get stuck with error as below:

>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [10 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\user\AppData\Local\Temp\pip-install-u5vik0hu\apischema_cfb95ac57f1b4346a4297a7d6a60f7ac\setup.py", line 101, in <module>
>           long_description=pathlib.Path("README.md").read_text(),
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
>           return f.read()
>                  ^^^^^^^^
>       UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 649: illegal multibyte sequence
>       [end of output]

Please advise.

**Comment by albertwong08** [comment]
I can finally install the library by including the PYTHONUTF8 environment variable.
