### ISSUE TITLE
How to fix solana.keypair module.

### ISSUE THREAD

**Issue by wkshare** [drift-labs/driftpy#63]
```
python3 floating_maker.py
Traceback (most recent call last):
  File "/Users/wangkai/workspace/init7/Drift/driftpy/examples/floating_maker.py", line 7, in <module>
    from solana.keypair import Keypair
ModuleNotFoundError: No module named 'solana.keypair'
```

I have solana module. but solana.keypair what is mean

**Comment by akasimo** [comment]
should work by using below instead:

from solders.keypair import Keypair

**Comment by wkshare** [comment]
same error:
```
>>> from solana.keypair import Keypair
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'solana.keypair'
```

**Comment by wkshare** [comment]
The SDK needs to update. 
to replace solders.keypair from solana.keypair.
